All Readthedocs structure and content in place
nasa/harmony-py pull request #24
Opened 2021-03-29 20:00 UTC by kbeamnsidc

This PR should build the docs on RTD...maybe?

2021-03-30 13:57 UTC, rwat commented on Makefile
> +	jupyter nbconvert --execute --to html --output notebook.html --output-dir docs/user $(docs-notebook)
It's awesome to be able to do this.

2021-03-30 14:03 UTC, rwat commented on docs/index.rst
> +
harmony_client should be instantiated here.

2021-03-30 15:25 UTC, rwat commented
When I tried 'make docs' it generated errors around not being able to find `harmony.cli`. I think this was a relic of some previous .rst files but you may want to verify you don't have them too, Kevin.

2021-03-30 15:37 UTC, rwat requested changes
Just a few things noted above.

2021-03-30 16:07 UTC, kbeamnsidc commented on .readthedocs.yml
> +   version: 3.7
For this version, I think it's just the version used when ReadTheDocs builds our documentation after the GitHub webhook, so it should be okay to set this to 3.7.

2021-03-30 16:25 UTC, rwat commented on docs/index.rst
> +
I'm sorry Kevin - you're right.

2021-04-01 20:25 UTC, bilts approved these changes
Nice!

2021-04-01 23:51 UTC, merged